name: 'Slack Jobs Status'
description: 'Notify Slack on workflow jobs summary status'
inputs:
  gh_ctx:
    description: 'GitHub context for worklfow run'
    required: true
  token:
    description: 'secrets.GITHUB_TOKEN'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
